/* IMPORTANT INSTRUCTIONS FOR LEARNERS
1) DO NOT CHANGE THE ORDER OF COLUMNS.
2) YOUR QUERY SHOULD DISPLAY COLUMNS IN THE SAME ORDER AS MENTIONED IN ALL QUESTIONS.
3) YOU CAN FIND THE ORDER OF COLUMNS IN QUESTION TEMPLATE SECTION OF EACH QUESTION.
4) USE ALIASING AS MENTIONED IN QUESTION TEMPLATE FOR ALL COLUMNS
5) DO NOT CHANGE COLUMN NAMES*/
                
-- Question 1 (Marks: 3)
-- Objective: Determine, for flights that actually departed later than scheduled, what the departure delay is (in minutes).
-- Calculate the Delay in Departures for Delayed Flights
-- Question Template: Display following columns flight_id, flight_no, departure_delay_minutes

Select flight_id, flight_no, timestampdiff(minute,scheduled_departure,actual_departure) as "departure_delay_minutes"
from Flights 
Where Scheduled_departure is not null
And actual_departure is not null 
And timestampdiff(minute,scheduled_departure,actual_departure) >0
Order By timestampdiff(minute,scheduled_departure,actual_departure) desc;

-- Question 2 (Marks: 3)
-- Objective: Show how frequently each aircraft is used by counting the number of flights operated by each aircraft.
-- List Flights Grouped by Aircraft to See Usage Frequency
-- Question Template: Display following columns aircraft_code, total_flights, avg_flight_duration_minutes

Select aircraft_Code, Count(Flight_Id) As total_flights, format(avg(timestampdiff(minute,scheduled_Departure,scheduled_arrival)),2) As avg_flight_duration_minutes
From Flights
Where Scheduled_Departure is not Null
And Scheduled_arrival is not Null
Group By Aircraft_Code;

-- Question 3 (Marks: 3)
-- Objective: Aggregate the total revenue generated by each flight by summing up the fare amounts from the ticket_flights table.
-- Calculate Total Revenue per Flight from the Ticket_Flights Table
-- Question Template: Display following columns flight_id, flight_no, total_revenue

Select F.flight_id as flight_id , F.flight_no as flight_no , Sum(TF.Amount) as total_revenue
From Flights as F join ticket_flights as TF
On F.Flight_id = TF.flight_id
Group By tf.Flight_Id , F.flight_no
order By total_revenue Desc;

-- Question 4 (Marks: 3)
-- Objective: Examine boarding pass data to identify how passengers are being boarded by calculating the average boarding number per flight.
-- Analyze Boarding Numbers per Flight to Detect Patterns in Boarding Pass Allocation
-- Question Template: Display following columns flight_id, avg_boarding_no, total_boarding_passes

Select flight_id, format(avg(boarding_no),2) as avg_boarding_no , count(boarding_no) as total_boarding_passes 
from boarding_passes
group by Flight_id;


-- Question 5 (Marks: 3)
-- Objective: Identify seat occupancy by comparing the number of boarding passes (occupied seats) to the total seats available on an aircraft.
-- Determine Occupancy per Aircraft
-- Question Template: Display following columns flight_id, flight_no, aircraft_code, total_seats,occupied_seats, occupancy_rate_percentage

With Seat_count as (
	Select aircraft_code, Count(*) As total_seats  From seats
    Group By aircraft_code
),
Occupied_Count as (
	Select flight_id, Count(*) As occupied_seats from Boarding_passes
    Group By Flight_id)
    
select F.Flight_id as flight_id, F.Flight_No as flight_no, 
F.Aircraft_Code as aircraft_code,total_seats, COALESCE(o.occupied_seats, 0) AS occupied_seats, 
round((COALESCE(o.occupied_seats, 0) *100.0 / total_seats),2) as occupancy_rate_percentage
From flights As F Join seat_count as S On F.aircraft_code = S.Aircraft_code
left Join Occupied_Count as o on F.flight_id = o.flight_id
Group By F.Flight_id, F.Flight_No, F.Aircraft_Code
order by occupancy_rate_percentage Desc;

-- Question 6 (Marks: 3)
-- Objective: Identify the three flights that generated the highest revenue based on ticket sales.
-- Top 3 Flights by Revenue
-- Question Template: Display following columns flight_id, flight_no, total_revenue
 
 Select F.flight_id as flight_id, f.flight_no as flight_no, sum(tf.amount) as total_revenue
 From flights as F join ticket_flights as tf
 on F.flight_id = tf.flight_id
 group By F.flight_id, f.flight_no
 Order by total_revenue desc 
 limit 3;

-- Question 7 (Marks: 3)
-- Objective: Determine the average flight duration for each aircraft model, allowing you to see how flight performance might vary between different models.
-- Average Flight Duration by Aircraft Model
-- Question Template: Display following columns model, avg_duration_minutes

Select A.Model as model, round(Avg(timestampdiff(minute,F.scheduled_departure,F.scheduled_arrival)),2) as avg_duration_minutes
from Flights as F join aircrafts as A
on F.aircraft_code = a.aircraft_code
Group by A.aircraft_code, A.model
order by avg_duration_minutes desc;

-- Question 8 (Marks: 3)
-- Objective: Count how many flights depart from each airport to assess airport activity levels.
-- Flight Count per Airport (Departure)
-- Question Template: Display following columns departure_airport, departure_flights

Select A.airport_name as departure_airport, Count(F.Flight_id) as departure_flights
From flights as F join airports as A
On F.departure_airport = A.airport_code
group by f.departure_airport
order by departure_flights desc;

-- Question 9 (Marks: 3)
-- Objective: Count how many flights depart from and arrive at each airport to assess airport activity levels.
-- Flight Count per Airport (Arrival)
-- Question Template: Display following columns arrival_airport, arrival_flights

Select A.airport_name as arrival_airport, Count(F.Flight_id) as arrival_flights
From flights as F join airports as A
On F.arrival_airport = A.airport_code
group by f.arrival_airport
order by arrival_flights desc;

-- Question 10 (Marks: 3)
-- Objective: Analyze trends in bookings over time by grouping bookings by date, counting total bookings, and summing up the revenue.
-- Daily Booking Trends
-- Question Template: Display following columns booking_date, total_bookings, total_revenue

Select date(book_date) as booking_date, 
Count(book_ref) as total_Bookings, Sum(total_amount) as total_revenue 
from bookings 
group by booking_date
order by booking_date desc;

-- Question 11 (Marks: 3)
-- Objective: Identify the most common routes by counting the number of flights for each departure–arrival airport pair.
-- Frequent Routes Analysis
-- Question Template: Display following columns departure_airport, arrival_airports, flights_count

Select dep.airport_name as departure_airport, arr.airport_name as arrival_airports, count(F.Flight_id) as flights_count
from flights as F join airports as dep join airports as arr
on F.departure_airport = dep.airport_code and F.arrival_airport = arr.airport_code
group by departure_airport, arrival_airports
order by flights_count desc
limit 10;

-- Question 12 (Marks: 3)
-- Objective: Determine how many passengers boarded each flight by counting the boarding passes issued.
-- Passenger Boarding Summary per Flight
-- Question Template: Display following columns flight_id, passengers_boarded

Select flight_id, Count(boarding_no) as passengers_boarded from boarding_passes
group By flight_id
Order by passengers_boarded desc ;

-- Question 13 (Marks: 3)
-- Objective: Assess the boarding process by calculating the average boarding order number for each flight, which may indicate the boarding strategy or sequence.
-- Average Boarding Number per Flight
-- Question Template: Display following columns flight_id, avg_boarding_no

Select flight_id, format(avg(boarding_no),0)as avg_boarding_no from boarding_passes
group By flight_id
Order by avg_boarding_no desc ;

-- Question 14 (Marks: 3)
-- Objective: Aggregate the total amount spent by each passenger across all their tickets by joining the tickets and ticket_flights tables.
-- Total Spend per Passenger
-- Question Template: Display following columns passenger_id, total_tickets, total_spent

select p.passenger_id as passenger_id, Count(P.ticket_no) as total_tickets , Sum(tf.amount) as total_spent
from tickets as P join ticket_flights as TF
on P.ticket_no = Tf.ticket_no
group by passenger_id
Order by total_spent desc;

-- Question 15 (Marks: 3)
-- Objective: Analyze the distribution of ticket volume and revenue across different fare conditions.
-- Fare?Condition Distribution
-- Question Template: Display following columns fare_conditions, tickets_sold, total_revenue

Select fare_conditions, Count(ticket_no) as tickets_sold , sum(amount) as total_revenue 
from ticket_flights
group by fare_conditions
order by total_revenue desc;

-- Question 16 (Marks: 3)
-- Objective: Aggregate total revenue generated by each departure?arrival airport route.
-- Revenue by Route
-- Question Template: Display following columns departure_airport, arrival_airport, total_route_revenue

Select 
	dep.airport_name as departure_airport, 
	arr.airport_name as arrival_airport, 
    sum(tf.amount) as total_route_revenue
from flights as F 
join airports as dep join airports as arr join ticket_flights as Tf
on f.departure_airport = dep.airport_code 
and f.arrival_airport = arr.airport_code 
and f.flight_id = Tf.flight_id
group by departure_airport, arrival_airport
order by total_route_revenue desc;

-- Question 17 (Marks: 2)
-- Objective: Identify the top 5 booking hours of the day by volume of bookings
-- Peak Booking Hours
-- Question Template: Display following columns booking_hour, bookings_count

select DATE_FORMAT(book_date, '%l %p') as booking_hour , count(book_ref) as bookings_count
from bookings 
group By booking_hour
order by count(book_ref) desc 
limit 5;

